#+TITLE: Resume
#+DATE: <2023-03-25>

* My Resume on the Web
:PROPERTIES:
:CUSTOM_ID: my-resume-on-the-web
:END:
While I am not actively searching for employment at the moment I'm always interested to hear about interesting projects. Please see my resume and of course please feel free to email me with any questions.

** Contact Information:
:PROPERTIES:
:CUSTOM_ID: contact-information
:END:
Gregory Silverstein

Bethlehem PA 18018

greg.silverstein@gmail.com

** Objectives:
:PROPERTIES:
:CUSTOM_ID: objectives
:END:
I look to work on /interesting/ software projects. Who doesn't! I enjoy working with people! Again I'd say who doesn't but I feel like that's not a common opening line. I've worked numerous roles from junior to staff engineer as well as multiple stints as Engineering and Product manager. I'm at my best empowering people. Whether that's improving what we implement, coaching junior engineers or ensuring stakeholders get the software they need.

** Education:
:PROPERTIES:
:CUSTOM_ID: education
:END:
Bachelor of Science, Computer Science

Stevens Institute of Technology, Hoboken NJ, 2001-2005

** Employment History
:PROPERTIES:
:CUSTOM_ID: employment-history
:END:
*** July 2025 -- Present Manager Software Engineering
:PROPERTIES:
:CUSTOM_ID: 2025-present-manager-software-engineering
:END:
HealthVerity, Philadelphia PA
Manage a team of five full time engineers and supervise a team of 8 contract engineers on various projects. I actively contribute to several code-bases while driving Agile ceremonies and managing performance for my team members. Tools used include AWS, CDK, Python, Typescript, Databricks, Atlassian Suite, generative AI, Claude Code.

*** September 2022 -- July 2025 Staff Software Engineer
:PROPERTIES:
:CUSTOM_ID: september-2022-2025-senior-software-engineer
:END:
HealthVerity, Philadelphia PA
Senior Engineer working on HealthVerity's privacy protection applications. Building HIPAA compliant applications to enable customers to gain insights from highly sensitive data. Tools used include AWS Server-less Components, AWS CDK, Python, JavaScript, R, Redis, Databricks.

*** December 2019 -- September 2022 Developer Data Engineering
:PROPERTIES:
:CUSTOM_ID: december-2019-september-2022-developer-data-engineering
:END:
Creditsafe USA, Allentown PA
Senior Data Engineer / Developer on a full stack team working multiple projects ranging from Creditsafe's US Web product to internal data analysis and cleansing. Performed agile ceremonies as scrum master and mentored junior developers and data analysts. Tools used include Oracle, Redshift, Python, SQL, PLSQL, Hive, Airflow.

*** Jan 2006 -- December 2019 Lead Programmer / Data Manager
:PROPERTIES:
:CUSTOM_ID: jan-2006-december-2019-lead-programmer-data-manager
:END:
Alight Solutions, Bridgewater NJ
Supervise, manage, cultivate and co-create SAS applications a medium sized team of developers. My team develops and creates SAS code ranging from end user data analysis to back end data scrubbing. data ranging from health insurance to 401k to retirement annuities. Additional tools used range from IBM System Z, JCL, Python and XML.

*** April 2004 - Jan 2006 Industrial Engineer
:PROPERTIES:
:CUSTOM_ID: april-2004---jan-2006-industrial-engineer
:END:
United Parcel Services, Parsippany and Saddlbrook NJ
Created VBA based SQL reports.

*** Skills
:PROPERTIES:
:CUSTOM_ID: skills
:END:
I'm a computer nerd but I will try to give a brief overview of what I am learning right now and also what I have a good deal of professional experience in.

*** Currently Learning
:PROPERTIES:
:CUSTOM_ID: currently-learning
:END:
Clojure, Common Lisp, Tic-80, Hugo Static Site Generator

*** Professional Experience
:PROPERTIES:
:CUSTOM_ID: professional-experience
:END:
Python, R, Javascript, Java, SQL, PLSQL, AWS, Azure Cloud, Git, Github, Gitops, Bash, Linux, Airflow, Hive, Redshift, Oracle, Databricks, IBM Z-OS, JCL, SAS, RDBMS, Project Management, Agile, Debugging and Testing
