#+TITLE: Open Source is not enough
#+DATE: <2023-09-18>

* The internet is becoming enshittified
:PROPERTIES:
:CUSTOM_ID: the-internet-is-becoming-enshittified
:END:
I've been giving a lot of thought in the past year or so to what I see as one of the many troubles of our time. Having the ever growing mass of humanity that spends its time online, completely un-educated about being on a computer.

/You know aside from the germs, global warming, endless wars and our continued tendency to crap all over anyone non-white cis male?/

Over the years I've heard countless anecdotes such as [[https://en.wikipedia.org/wiki/Eternal_September][Eternal September]] bemoaning the constant flux of new and uneducated internet citizens. I've also seen professionally the issues caused by our less than perfect system for educating people on computers. The constant take away of this is that the "masses" are causing [[https://en.wiktionary.org/wiki/enshittification][enshittification]] and its all their fault.

Except mostly its ours and all we want to do is make excuses. We have great tools, we have open source, we have... X formerly known as twitter?

* Open source is not enough
:PROPERTIES:
:CUSTOM_ID: open-source-is-not-enough
:END:
Shit

It's simply not. I remember my first foray into open computing. I started poking around IRC on a computer that was using AOL dial up. My brain exploded, the idea of people just sharing information and in my case at the time music blew my mind. I spent hours reading help files and honestly the curiosity to explore hidden rooms never left. I'll probably die getting stuck trying to find my way into some new secret library.

People don't read things just because they exist. They don't learn math just because a book titled Math is in their backpack. Open source is a great ethos but its just one step in the game. We need to do better than just making things available. We need to share and encourage people to open the door.

When you read a book story what encourages the the eager to adventure? Do Merry and Pippin head off to far lands on the premise of someone calling them a [[https://github.com/corollari/linusrants][fucking idiot]]? Do they go just because Gondor exists? Of course not they follow the kind urging of Gandalf and the company of friends they trust. They go and despite learning the pain of war they help save their little world.

Why are we then shocked that people flock to the internet to argue, fight and shit absolutely everywhere? We hand them a phone made by Sundar Pichai or Tim Cook generally designed to suck money from them any way possible. Even if that means they melt the planet and literally scream at [[https://www.insider.com/girl-left-sobbing-man-accused-her-of-being-trans-athletics-2023-6][transgender children]]. We have tools and books available to them hidden off in the far reaches of the ether with no sign posts or maps. We complain that people do not understand the basics of [[https://en.wikipedia.org/wiki/Golden_Rule][kindness]]. We complain that newer developers just churn out "CRUD apps in react" and yet no one sits down with them for three months and goes through [[https://web.mit.edu/6.001/6.037/sicp.pdf][the wizard book]].

The adventure isn't there if we do not put people on the path to it.

* Putting people on a path
:PROPERTIES:
:CUSTOM_ID: putting-people-on-a-path
:END:
We cannot simply wish or force people into better online discourse and understanding of the world we've created in the past 20 years. We need to put them on the course for adventure rather than milking them for money and then complaining they behave as a cow would.

I'm writing this post from a steam deck. Why? Because it asked me to try it. When young people are handed an iPad, when does it ever direct them to what lies underneath? Swift playgrounds? Barf. When does it suggest they do anything other than what sells? The steam deck has the wonderful gem of switch to desktop mode. Konsole is there. It probably makes Valve zero extra money. It asks you to come check out what lies beneath and within 2 hours of playing games on mine I was seeing if I could install Hugo and touch my deserted blog.

This is the type of thing we need to build more and more of. Valve seems to get it, how can we have them teach Apple or Microsoft? Can we or is the profit motive too much? Why doesn't the xbox or iPad or iPhone encourage users into developer mode?

More importantly what can you and I do each day to help with this? How do we redirect people to better ways?

I'm genuinely asking. Its on my mind and I absolutely have no complete answers. I'd love to [[https://hachyderm.io/@pokeypoke][speak about it with anyone]] and if we have a good idea who knows do something actually about the mess together.

Later!
