#+TITLE: SteamDeck Fun
#+DATE: <2023-09-20>

* SteamDeck Fun
:PROPERTIES:
:CUSTOM_ID: steamdeck-fun
:END:
The steam deck really is a great device to poke around on. It's funky as someone with Linux experience, it is very open but it has some opinionated setup from Valve. For example it [[https://www.phoronix.com/review/steam-deck-steamos-linux][uses an A/B scheme]] to roll back updates and this makes installing anything with Pamac/Pacman weird.

At the same point these things are kind of fun. It's a new cave to explore.

* SteamDeck as an adventure
:PROPERTIES:
:CUSTOM_ID: steamdeck-as-an-adventure
:END:
Things like this make me wonder if a SteamDeck would be a better teaching tool than some of the things we commonly hand kids. Does a Chromebook or iPad ever teach you to dig in? An open but managed device like a SteamDeck lets you get in easily, the SteamOS is a polished console if you don't go under the surface.

While not free and not available to every child in the US or world as a whole a SteamDeck is close to that magic price point of $3-500 where educational institutions could use it. Likewise its close to that price point of the Nintendo Switch where it can be purchased for a child where an Xbox is a larger purchase.

You could imagine a sort of course plan structured to have a new learner go from gaming to learning computing to programming their own games. You hand them a switch, a USBC hub, a keyboard and a mouse and they could go through a chain.

1. Get deck, install a game
2. Play the game and tweak settings like TDP and frame rate to increase battery life.
3. Adjust the controls to make the game "yours".
4. Set up developer mode and go to the desktop.
5. Install an app like a music player.
6. Install a text editor (vs code, vim, Emacs).
7. Install Python
8. Python programming basics
9. Install Godot
10. Make a game and play it on the switch.

Imagine that instead of whatever happens on a Chromebook. Log in and YouTube?

* Adventure for the experienced
:PROPERTIES:
:CUSTOM_ID: adventure-for-the-experienced
:END:
The SteamDeck is also great for the more experienced. Here's an example for myself, I always wish for something smaller than a laptop that I can take Emacs and my org agenda to go with.

I've gotten Emacs installed on my deck via flatpack. Doom Emacs doesn't seem to work with the deck out of the box, but who cares I'm hand rolling a config. The next best part? Using "add to steam" Emacs can be accessible from the Steam launcher.

From there I can remap the controller to have specific controls (say M-x Org Agenda) on the controller. I'm very close to being able to have my org agenda available on a portable touch screen device with no keyboard.

This project may sound awful to you, and that's fine, the point being the device enables such adventures.

* Reach Out
:PROPERTIES:
:CUSTOM_ID: reach-out
:END:
You can reach out to me if you want to talk about this. I'd love to [[https://hachyderm.io/@pokeypoke][speak about it with anyone]].

Later!
