#+TITLE: Random Thoughts
#+DATE: <2026-08-20 Thu>
#+DESCRIPTION: A brain dump as I learn to live with AI

* Yo

I haven't blogged in a while but I've wanted to. I think its en vogue right now to just let AI post for you, but this is me typos and weird Jersey-ism's will follow. It's hard to keep this kind of habit in 2026, at least for me. There seem to be endless calls to your attention, I know that complaint has been popular for a decade with social media but for me its worse in 2026 because I can be distracted by making things. While I'm not allowing Claude or some other model make this post, Claude is open underneath it. I'm still in emacs writing in Claude code but a "EAT" terminal with Claude is open in a window below this one. Claude is explaining to me how to use this new blogging setup because with Claude I did something I've wanted for years, to blog with just Emacs.

I guess I'm just now going to find out, did it work.

** AI is weird.

I want to hate it. LLMs are wreaking havoc on my profession. A year ago I was hand rolling a basic coding agent using Boto3 and Pydantic AI at the day job because my leadership was not allowing use of Claude Code or anything short of chatGPT on a web site. Today I'm wondering when I am going to know people terminated for not using enough tokens. People are shipping absolute trash and doing inconsiderate things like copy pasting chat GPT to their parents when they ask a question. On the other hand people are making things who couldn't before. All through my career I've been most proud when I take someone who can't get what they want out of a computer and get it. Teaching a data entry person to use SQL, teaching a beginner programmer interfaces. Seeing non-engineers in my workplace ship their own application has been pretty awesome. Helping them do so even better.

Each day I'm torn between being happy with something newly created, being concerned for long standing projects degrading or being enraged when someone is just truly lazy and seeking a reward for it.

I sort of live in fear that someone will sloppify Emacs and burn it down.

** It was confusing enough at work but....

I took it home with me. I HATE Strava. I find the plethora of SaaS apps that ask for a fee for static software immoral. So I took Claude home with me and made [[https://github.com/gsilvers/err][err]]. I've learned a bit about Flutter/Dart and I'd say testing these things out physically in the world and finding bugs in this app is far from slop. Is it bad to get rid of a dependency on an app by paying for a month or two of a worse company ethically? 

* Fin

I feel like I'm starting to get close to an understanding, or at least a modus operandi with LLMs. Like fire however if you give it to someone without foresight, well your house may burn down. I think you can use LLM's to make things. But I'm really converging on its not that much faster, and it wouldn't be any faster if we had more people teaching and writing great documentation. It certainly isn't any good if you don't read and understand what you built. It's not an application if you need a Claude subscription to maintain it. Once I get a little more grounded in experience I"m going to try to write some more distilled and cogent thoughts on this.

For now I'd leave anyone who reads this with an ask. Don't be a piece of shit. Don't fire people over low AI metrics, its too soon to know what productive and maintainable looks like when people are slinging gobs of code out. If you're anti AI, remember the position of the person you may quarrel with. By all means argue with Sam Altman, but if your coworker is just keeping their head down and prompting away, remember they may have a sick kid at home. Whatever you do, don't copy paste LLM stuff to other humans its rude.
